name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    permissions: write-all
    runs-on: macos-latest # 根据需要选择操作系统
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: 先安装web依赖
        run: npm install --prefix web
      - name: 再打包web
        run: npm run build  --prefix web
      - name: 再安装electron依赖
        run: npm install
      - name: 再安装electron
        run: npm run make
      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/make/*
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}